spring.application.name=shopkart

spring.datasource.url= jdbc:postgresql://localhost:5432/localdb?currentSchema=shopkart_db
spring.datasource.username= postgres
spring.datasource.password= Galaxy@123


app.jwt.secret.key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007bfwsfw323sdfsdf32432fdsf
app.jwt.expiration=900000
app.jwt.refresh=604800000



spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql: false
spring.jpa.properties.hibernate.order_inserts: true
spring.jpa.properties.hibernate.generate_statistics: false
spring.jpa.show-sql: true
#spring.jpa.hibernate.ddl-auto=update